dishflow/config/routes.rb
Rails.application.routes.draw do

  resources :special_dishes
  resources :ratings
  devise_for :users do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :accounts

  root to: "statics#home"

  resources :recipes

  resources :menus do

    resources :lists do
      member do
        patch  :move
      end
    end

    resources :foods do
      member do
        patch  :move
      end

      resources :reviews
    end
  end

  get "/", to: "statics#home", as: :home

end

dishflow/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :owner, class_name: "User"
  accepts_nested_attributes_for :owner

  has_many :menus
end

dishflow/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dishflow/app/models/dish.rb
class Dish < ApplicationRecord
  acts_as_list scope: :menu

  belongs_to :menu

  validates :name, presence: true
end

dishflow/app/models/food.rb
class Food < ApplicationRecord
  has_rich_text :body
  acts_as_list scope: :list

  belongs_to :list

  has_many :reviews

  validates_presence_of :name, {minimum: 5, maximum: 30}
end

dishflow/app/models/list.rb
class List < ApplicationRecord
  acts_as_list

  belongs_to :menu
  has_many :foods, ->{ order(position: :asc) }, dependent: :destroy

  scope :sorted, ->{ order(position: :asc)}
  validates :name, presence: true

  accepts_nested_attributes_for :foods, allow_destroy: true

end

dishflow/app/models/menu.rb
class Menu < ApplicationRecord
  has_rich_text :body
  validates_presence_of :name, {minimum: 5, maximum: 30}

  has_many :lists
  has_many :menu_recipes
  has_many :recipes, through: :menu_recipes
  has_many :reviews
  has_many :ratings
  accepts_nested_attributes_for :ratings, allow_destroy: true
end

dishflow/app/models/menu_recipe.rb
class MenuRecipe < ApplicationRecord
  belongs_to :menu, optional: true
  belongs_to :recipe, optional: true
end

dishflow/app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :menu
end

dishflow/app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :menu_recipes
  has_many :menus, through: :menu_recipes

  has_rich_text :body

  validates_presence_of :name, {minimum: 5, maximum: 30}
end

dishflow/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food
  belongs_to :menu
  serialize :properties, Hash
end

dishflow/app/models/special_dish.rb
class SpecialDish < ApplicationRecord
end

dishflow/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

dishflow/app/helpers/accounts_helper.rb
module AccountsHelper
end

dishflow/app/helpers/application_helper.rb
module ApplicationHelper
end

dishflow/app/helpers/foods_helper.rb
module FoodsHelper
end

dishflow/app/helpers/lists_helper.rb
module ListsHelper
end

dishflow/app/helpers/menus_helper.rb
module MenusHelper
end

dishflow/app/helpers/ratings_helper.rb
module RatingsHelper
end

dishflow/app/helpers/recipes_helper.rb
module RecipesHelper
end

dishflow/app/helpers/reviews_helper.rb
module ReviewsHelper
end

dishflow/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

dishflow/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light white-bg shadow sticky-top">
  <%= link_to "DishFlow", root_path, class: "nav-link navbar-brand bold" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "recipes", recipes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "menus", menus_path, class: "nav-link" %>
      </li>

    </ul>

    <% if user_signed_in? %>
      <li class="nav-item list-unstyled">
        <%= link_to 'log out',  destroy_user_session_path, :method => :delete, data: {confirm: 'Are you sure you want to log out?'}, class: "btn btn-dark" %>
        <!-- <a class="nav-link" href="#">Features</a> -->
      </li>
    <% else %>
      <%= link_to 'Log in',  new_user_session_path, class: "btn btn-light" %>

      <%= link_to 'Sign up',  new_account_path, class: "btn btn-light" %>
    <% end %>
  </div>
</nav>

dishflow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dishflow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>