dishflow/config/routes.rb
Rails.application.routes.draw do

  resources :special_dishes
  resources :ratings
  devise_for :users do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :accounts

  root to: "statics#home"

  resources :recipes

  resources :menus do

    resources :lists do
      member do
        patch  :move
      end
    end

    resources :foods do
      member do
        patch  :move
      end

      resources :reviews
    end
  end

  get "/", to: "statics#home", as: :home

end

dishflow/app/models/account.rb
class Account < ApplicationRecord
  belongs_to :owner, class_name: "User"
  accepts_nested_attributes_for :owner

  has_many :menus
end

dishflow/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dishflow/app/models/dish.rb
class Dish < ApplicationRecord
  acts_as_list scope: :menu

  belongs_to :menu

  validates :name, presence: true
end

dishflow/app/models/food.rb
class Food < ApplicationRecord
  has_rich_text :body
  acts_as_list scope: :list

  belongs_to :list

  has_many :reviews

  validates_presence_of :name, {minimum: 5, maximum: 30}
end

dishflow/app/models/list.rb
class List < ApplicationRecord
  acts_as_list

  belongs_to :menu
  has_many :foods, ->{ order(position: :asc) }, dependent: :destroy

  scope :sorted, ->{ order(position: :asc)}
  validates :name, presence: true

  accepts_nested_attributes_for :foods, allow_destroy: true

end

dishflow/app/models/menu.rb
class Menu < ApplicationRecord
  has_rich_text :body
  validates_presence_of :name, {minimum: 5, maximum: 30}

  has_many :lists
  has_many :menu_recipes
  has_many :recipes, through: :menu_recipes
  has_many :reviews
  has_many :ratings
  accepts_nested_attributes_for :ratings, allow_destroy: true
end

dishflow/app/models/menu_recipe.rb
class MenuRecipe < ApplicationRecord
  belongs_to :menu, optional: true
  belongs_to :recipe, optional: true
end

dishflow/app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :menu
end

dishflow/app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :menu_recipes
  has_many :menus, through: :menu_recipes

  has_rich_text :body

  validates_presence_of :name, {minimum: 5, maximum: 30}
end

dishflow/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :food
  belongs_to :menu
  serialize :properties, Hash
end

dishflow/app/models/special_dish.rb
class SpecialDish < ApplicationRecord
end

dishflow/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

dishflow/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy, :move]
  before_action :set_menu

  def index
    @foods = @menu.foods.sorted
  end

  def show
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = @menu.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to menu_food_path(@menu, @food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy!
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @food.update(food_params)
    render action: :show
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:menu_id, :name, :body, :description, :price, :position, :list_id)
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end
end

dishflow/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_menu
  before_action :set_list, only: [:show, :edit, :update, :destroy, :move]

  def index
    @lists = @menu.lists.sorted
  end

  def show
  end

  def new
    @list = @menu.lists.build
  end

  def edit; end

  def create
    @list = @menu.lists.new(list_params)
    respond_to do |format|
      if @list.save

        # ActionCable.server.broadcast "board", { commit: 'addList', payload: render_to_string(:show, format: :json) }

        format.html { redirect_to menu_lists_path(@menu, @lists), notice: "You have a created a new list!" }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def move
    @list.insert_at(list_params[:position].to_i)
    render action: :show
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to menu_lists_path(@menu, @lists), notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    redirect_to menu_path(@menu), notice: 'List was successfully destroyed.'
    # respond_to do |format|
    #   format.html { redirect_to menu_path(@menu), notice: 'List was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private

  def set_list
    @list = @menu.lists.find(params[:id])
  end

  def set_menu
    @menu = Menu.find(params[:menu_id])
  end

  def list_params
    params.require(:list).permit(:id, :name, :body, :position, :description, :menu_id, foods_attributes: [:id, :name, :position, :_destroy])
  end
end

dishflow/app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy, :move]

  def index
    @menus = Menu.all
  end

  def show
  end

  def new
    @menu = Menu.new
  end

  def edit
  end

  def create

    @menu = Menu.new(menu_params)
    @menu.account_id = current_user.id
    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def move
    @menu.insert_at(menu_params[:position].to_i)
  end

  private

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:name, :position, :body, :account_id, ratings_attributes: [:id, :_destroy, :name, :description])
  end

end

dishflow/app/helpers/accounts_helper.rb
module AccountsHelper
end

dishflow/app/helpers/application_helper.rb
module ApplicationHelper
end

dishflow/app/helpers/foods_helper.rb
module FoodsHelper
end

dishflow/app/helpers/lists_helper.rb
module ListsHelper
end

dishflow/app/helpers/menus_helper.rb
module MenusHelper
end

dishflow/app/helpers/ratings_helper.rb
module RatingsHelper
end

dishflow/app/helpers/recipes_helper.rb
module RecipesHelper
end

dishflow/app/helpers/reviews_helper.rb
module ReviewsHelper
end

dishflow/app/views/foods/_form.html.erb
<%= simple_form_for [@menu, @food] do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "enter name" %>
  </div>
  <br  />
  <div class="field">
    <%= form.text_field :price, placeholder: "enter price" %>
  </div>
  <br  />
  <div class="field">
    <%= form.rich_text_area :body, placeholder: "enter description" %>
  </div>
  <br  />
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-dark" %>
    
  </div>

<% end %>

dishflow/app/views/foods/edit.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h4 class="bold "><%= link_to "Edit Food", menu_food_path %></h4>
    
    <div class="card p-5">
      <%= render 'form', food: @food %>
      <br  />
    </div>

  </div>

</div>

dishflow/app/views/foods/index.html.erb
<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Menu</th>
      <th>Name</th>
      <th>Description</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.menu_id %></td>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.position %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

dishflow/app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

dishflow/app/views/foods/show.html.erb
<%= link_to "#{@menu.name}", menu_path(@menu), class: "small-bold" %> - <%= link_to "list", [@menu, @list], class: "small-bold" %>
<br  />

<%= link_to "edit", edit_menu_food_path(@menu, @food), class: "small-bold" %>
<%= link_to "delete", menu_food_path, method: :delete, data: { confirm: "Are you sure you want to delete #{@food.name}? "}, class: "small-bold" %>
<br  />
<br  />
<div class="card p-5 text-center">
  <p>
    <h5 class="bold"><%= @food.name %></h4>
    <p>$ <%= @food.price %></p>
    <%= @food.body %>
  </p>
  <br  />
  <%= link_to "Reviews", menu_food_reviews_path(@menu, @food, @reviews), class: "bold" %>
  <div class="row">
    <% @food.reviews.last(5).each do |review| %>
      <div class="col-md-4">
        <div class='card p-4'>
          <%= truncate(review.public, length:100) %>
        </div>

      </div>
    <% end %>
  </div>

</div>

dishflow/app/views/menus/_form.html.erb
<%= content_tag :div,
    id: "menu-form",
    data: {
      id: menu.id,
      menu: menu.to_json(except: [:id, :created_at, :updated_at]),
      ratings_attributes: menu.ratings.to_json(except: [:menu_id, :created_at, :updated_at]),
    } do %>

    <h4 class="bold">Menu Name</h4>
    <input type="text" v-model="menu.name" />
    <br />
    <br />
    <h5 class="bold">Ratings</h5>
    <div v-for="(rating, index) in menu.ratings_attributes">
      <div v-if="rating._destroy == '1' ">
        {{ rating.name }} will be removed. <button v-on:click="cancelRemove(index)" class="btn btn-dark">Undo</button>
      </div>
      <div v-else>
        <h6 class="bold">Name</h6>
        <input type="text" v-model="rating.name" />

        <button v-on:click="removeRating(index)" class="btn btn-dark">Remove</button>
      </div>
      <br  />
    </div>

    <button v-on:click="addRating" class="btn btn-dark">Add Rating</button>
    <br />
    <br />
    <button v-on:click="saveMenu" class="btn btn-dark">Save Menu</button>
<% end %>




<!--
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.text_field :name, placeholder: "enter name" %>
    <br />
    <br />
    <%= form.rich_text_area :body %>
  </div>
  <br />
  <%= form.button "submit", class: "btn btn-dark" %>

<% end %>
  -->

dishflow/app/views/menus/edit.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <h4 class="bold"><%= link_to @menu.name, @menu %></h4>
    <div class="card p-5">
      <%= render 'form', menu: @menu, class: "btn btn-dark" %>
    </div>
  </div>
</div>

dishflow/app/views/menus/index.html.erb
<div class="row">
  <div class="col-7">
    <p class="menu-main-header mb-3">Menus</p>
    <p class="menu-paragraph">
      Part of the magic of iPad is that almost anything can be done with Multi-Touch using simple, intuitive gestures. And now iPadOS makes it easier and faster to select and edit text using just your fingers.
    </p>
    <%= link_to 'Create new menu',  new_menu_path, class: "btn btn-dark mb-4" %>
  </div>
  <div class="col-5">

  </div>
  <% @menus.each do |menu| %>
    <div class="col-md-3">
      <div class="card p-4">
        <p class="bold">
          <%= link_to menu.name, menu_path(menu) %>
        </p>
      </div>
      <br  />
    </div>
  <% end %>
</div>

dishflow/app/views/menus/new.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <h4 class="bold"><%= link_to "Menus", menus_path %></h4>
    <div class="card p-5">

      <%= render 'form', menu: @menu %>
    </div>

  </div>
</div>

dishflow/app/views/menus/show.html.erb
<div class="mb-3">
  <p class="menu-main-header mb-0"><%= @menu.name %></p>
  <h5><%= @menu.body %></h5>
  <% @menu.ratings.each do |rating| %>
    <%= rating.name %>
  <% end %>
</div>

<%= link_to "Add Group", new_menu_list_path(@menu, @list), class:"btn btn-dark" %>
<%= link_to "Preview", menu_lists_path(@menu), class:"btn btn-dark" %>


<div class="row mt-5">
  <% @menu.lists.each do |list| %>
    <div class="col-md-4">
      <div class="card p-4">
        <p class="bold"><%= link_to list.name, menu_list_path(@menu, list) %></p>
      </div>
      <br  />
    </div>

  <% end %>
</div>
<hr  />
<%= link_to 'Edit', edit_menu_path(@menu), class:"btn btn-dark" %>
<%= link_to 'Back', menus_path, class:"btn btn-dark" %>